baseURL = 'https://biancawentzel.github.io'
languageCode = 'de'
paginate = 6
theme= "coHub"
title = 'Sinfonietta Charlottenburg'
publishDir = "docs"
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Programm"
  url = "#aktuelles-programm"
  weight = 1
  [[menu.Main]]
  name = "Orchester"
  url= "#orchester"
  weight = 2
  [[menu.Main]]
  name = "Dirigent"
  url= "#dirigent"
  weight = 3
  [[menu.Main]]
  name = "Konzerte"
  url= "#konzerte"
  weight = 4
  [[menu.Main]]
  name = "Proben"
  url = "#proben"
  weight = 5
  [[menu.Main]]
  name = "Kontakt"
  url= "/contact/"
  weight = 6

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Datenschutzerklaerung"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Impressum"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Sinfonietta Charlottenburg"
  fabFormURL =  ""
  googleAnalytics = ""
  logo = "images/sinfonietta-logo.svg"
  footerlogo = "images/sinfonietta-logo.svg"
  footerDescription = "Sinfonietta Charlottenburg - Ein Berliner Laienorchester"

  [params.address]
  address = "Hildegard-Wegscheider-Gymnasium<br> Lassenstr. 16-20<br> 14193 Berlin "
  email = ""
  openingDesc = "Musikerinnen und Musiker, die ein Berliner Amateurorchester suchen, sind bei der Sinfonietta Charlottenburg gern gesehen. Wer interessiert ist, kann gerne bei einer Probe zuschauen oder noch besser gleich mitspielen."
  openingHours = "Wir proben jeden Donnerstag von 19:00 Uhr bis 21:30 Uhr"
  phone = ""

  # Socail icons
  [[params.social]]
  icon = ""
  url = ""
  weight = 1
  [[params.social]]
  icon = ""
  url = ""
  weight = 2
  [[params.social]]
  icon = ""
  url = ""
  weight = 3
  [[params.social]]
  icon = ""
  url = ""
  weight = 4
  
  
